"""Add customer_id to User

Revision ID: 6cc5a516ea67
Revises: a9f3c2e1b7d4
Create Date: 2026-06-23 10:26:41.461750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cc5a516ea67'
down_revision: Union[str, Sequence[str], None] = 'a9f3c2e1b7d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'customer_id')
    # ### end Alembic commands ###
